### ISSUE TITLE
ImportError: DLL load failed while importing slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0: 找不到指定的模块。

### ISSUE THREAD

**Issue by leezhien** [NX-AI/xlstm#37]
'verbose': True, 'with_cuda': True, 'extra_ldflags': ['-LD:\\CUDA_manager\\CUDA12.0\\CUDA1\\lib', '-lcublas'], 'extra_cflags': ['-DSLSTM_HIDDEN_SIZE=64', '-DSLSTM_BATCH_SIZE=8', '-DSLSTM_NUM_HEADS=1', '-DSLSTM_NUM_STATES=4', '-DSLSTM_DTYPE_B=float', '-DSLSTM_DTYPE_R=__nv_bfloat16', '-DSLSTM_DTYPE_W=__nv_bfloat16', '-DSLSTM_DTYPE_G=__nv_bfloat16', '-DSLSTM_DTYPE_S=__nv_bfloat16', '-DSLSTM_DTYPE_A=float', '-DSLSTM_NUM_GATES=4', '-DSLSTM_SIMPLE_AGG=true', '-DSLSTM_GRADIENT_RECURRENT_CLIPVAL_VALID=false', '-DSLSTM_GRADIENT_RECURRENT_CLIPVAL=0.0', '-DSLSTM_FORWARD_CLIPVAL_VALID=false', '-DSLSTM_FORWARD_CLIPVAL=0.0', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_BFLOAT16_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__', '-U__CUDA_NO_BFLOAT162_OPERATORS__', '-U__CUDA_NO_BFLOAT162_CONVERSIONS__'], 'extra_cuda_cflags': ['-Xptxas="-v"', '-gencode', 'arch=compute_80,code=compute_80', '-res-usage', '--use_fast_math', '-O3', '-Xptxas -O3', '--extra-device-vectorization', '-DSLSTM_HIDDEN_SIZE=64', '-DSLSTM_BATCH_SIZE=8', '-DSLSTM_NUM_HEADS=1', '-DSLSTM_NUM_STATES=4', '-DSLSTM_DTYPE_B=float', '-DSLSTM_DTYPE_R=__nv_bfloat16', '-DSLSTM_DTYPE_W=__nv_bfloat16', '-DSLSTM_DTYPE_G=__nv_bfloat16', '-DSLSTM_DTYPE_S=__nv_bfloat16', '-DSLSTM_DTYPE_A=float', '-DSLSTM_NUM_GATES=4', '-DSLSTM_SIMPLE_AGG=true', '-DSLSTM_GRADIENT_RECURRENT_CLIPVAL_VALID=false', '-DSLSTM_GRADIENT_RECURRENT_CLIPVAL=0.0', '-DSLSTM_FORWARD_CLIPVAL_VALID=false', '-DSLSTM_FORWARD_CLIPVAL=0.0', '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_BFLOAT16_OPERATORS__', '-U__CUDA_NO_BFLOAT16_CONVERSIONS__', '-U__CUDA_NO_BFLOAT162_OPERATORS__', '-U__CUDA_NO_BFLOAT162_CONVERSIONS__']}
Using C:\Users\a\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu118 as PyTorch extensions root...
Creating extension directory C:\Users\a\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu118\slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\a\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu118\slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0\build.ninja...
Building extension module slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.11.1.git.kitware.jobserver-1
Loading extension module slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0...
Traceback (most recent call last):
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\experiments\main.py", line 155, in <module>
    main(cfg)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\experiments\main.py", line 51, in main
    model = xLSTMLMModel(from_dict(xLSTMLMModelConfig, OmegaConf.to_container(cfg.model))).to(
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\xlstm_lm_model.py", line 29, in __init__
    self.xlstm_block_stack = xLSTMBlockStack(config=config)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\xlstm_block_stack.py", line 83, in __init__
    self.blocks = self._create_blocks(config=config)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\xlstm_block_stack.py", line 104, in _create_blocks
    blocks.append(sLSTMBlock(config=config))
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\block.py", line 32, in __init__
    super().__init__(
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\xlstm_block.py", line 62, in __init__
    self.xlstm = sLSTMLayer(config=self.config.slstm)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\layer.py", line 78, in __init__
    self.slstm_cell = sLSTMCell(self.config)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\cell.py", line 780, in __new__
    return sLSTMCell_cuda(config, skip_backend_init=skip_backend_init)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\cell.py", line 690, in __init__
    self.func = sLSTMCellFuncGenerator(self.training, config)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\cell.py", line 536, in sLSTMCellFuncGenerator
    slstm_cuda = sLSTMCellCUDA.instance(config=config)
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\cell.py", line 515, in instance
    cls.mod[repr(config)] = load(
  File "C:\Users\a\Downloads\xlstm-main\xlstm-main\xlstm\blocks\slstm\src\cuda_init.py", line 84, in load
    mod = _load(name + suffix, sources, **myargs)
  File "D:\Users\a\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1285, in load
    return _jit_compile(
  File "D:\Users\a\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1536, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Users\a\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1931, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing slstm_HS64BS8NH1NS4DBfDRbDWbDGbDSbDAfNG4SA1GRCV0GRC0d0FCV0FC0d0: 找不到指定的模块。
how do deal it?

**Comment by leezhien** [comment]
I think slstm is not work,I can run parity_xlstm01.yaml,but 11 is not work

**Comment by Supersource666** [comment]
have you solved it?

**Comment by kpoeppel** [comment]
Have you tried with the updated conda environment?

**Comment by xunyoyo** [comment]
Have same question

**Comment by Peng-DX** [comment]
how to address this problem

**Comment by xunyoyo** [comment]
Using another github repo to replace this maybe a good way. 




xunyoyo
***@***.***
